# Tên ứng dụng và port
spring.application.name=parking-backend
server.port=8080

# Cấu hình DataSource (MySQL)
# Dùng tên database theo plan: parking_db
spring.datasource.url=jdbc:mysql://localhost:3306/parking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# UserName máy chủ MySQL chạy ở local mặc định thường là root, cần đổi pass này nếu máy cài pass đặc thù
spring.datasource.username=root
spring.datasource.password=123456

# Hibernate JPA Settings
# Tự động tạo bảng (update) dựa trên Code Entity hoặc (create) nếu chưa có
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
